<div class="jumbotron">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h2><?php echo sprintf($this->translate('%s[MyApplication]%s setup - Installation'), '<span class="appname">', '</span>') ?></h2>
    <br />
    <p>
        <?php echo $this->translate('here comes the installation module...'); ?>
    </p>
    <br />
    <hr />
    <br />
    <p>
        <?php echo sprintf($this->translate('server: %s, %s'), $_SERVER["SERVER_ADDR"], $_SERVER["SERVER_ADMIN"]); ?><br />
        <?php echo sprintf($this->translate('system: %s, %s'), $_SERVER["SERVER_SOFTWARE"], $_SERVER["GATEWAY_INTERFACE"]); ?><br />
        <?php echo sprintf($this->translate('php: v%s'), phpversion()); ?><br />
        <?php echo sprintf($this->translate('ZendFramework2: v%s'), \Zend\Version\Version::VERSION); ?>
     </p>
    <br />
</div>
