<?php 
	echo $this->doctype(); 
	/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $oTwitterBootstrap **/
	$oTwitterBootstrap = $this->bootstrap();
	/** @var \TwitterBootstrapAPI\View\Helper\Components $oComponents **/
	$oComponents = $this->Components();
	/** @var \Admin\Entity\User $user **/
	$oUser = $this->zfcUserIdentity();
?>
<html class="no-js" lang="<?php echo \Locale::getPrimaryLanguage(null) ?>">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('[BB] '. $this->translate($oTwitterBootstrap->AppTitle()))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- styles -->
        <?php 
        	$themePath = "themes/foundation/assets/";
        	$this->headLink(array(
        			'rel' => 'shortcut icon', 
        			'type' => 'image/vnd.microsoft.icon', 
        			'href' => $this->basePath($themePath . $oTwitterBootstrap->AppFavicon())
        			//'href' => '/'.$oTwitterBootstrap->AppFavicon()
     			))
				->appendStylesheet($this->basePath($themePath . 'css/foundation.min.css'))
			    ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
				->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css')
				->appendStylesheet($this->basePath($themePath . 'js/datatables/css/dataTables.foundation.min.css'))
				->appendStylesheet($this->basePath($themePath . 'css/flag-icon-css/flag-icon.min.css'))
				->appendStylesheet($this->basePath($themePath . 'css/app.css'))
        	;
            $cssfiles = $oTwitterBootstrap->Config()->get('app')->get('css');
            if (is_array($cssfiles) || ($cssfiles instanceof \Zend\Config\Config)) foreach ($cssfiles as $key => $file) {
                $this->headLink()->appendStylesheet($this->basePath($file));
            }
        	echo $this->headLink();
        	/*echo $this->headscript()
        	;*/
		?>
		<?php 
        	$this->headScript()
        		->appendFile($this->basePath($themePath . 'js/modernizr.js'))
				->appendFile($this->basePath($themePath . 'js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
				->appendFile($this->basePath($themePath . 'js/jquery.js'))
				//->appendFile($this->basePath($themePath . 'js/vendor/fastclick.js'))
				//->appendFile($this->basePath($themePath . 'js/foundation/foundation.js'))
				/*->appendFile($this->basePath($themePath . 'js/foundation/foundation.abide.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.accordion.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.alert.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.clearing.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.dropdown.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.equalizer.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.interchange.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.joyride.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.magellan.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.offcanvas.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.orbit.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.reveal.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.slider.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.tab.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.tooltip.js'))
				->appendFile($this->basePath($themePath . 'js/foundation/foundation.topbar.js'))*/
				//->appendFile($this->basePath($themePath . 'js/foundation.js'))
				->appendFile($this->basePath($themePath . 'js/foundation.min.js'))
				->appendFile($this->basePath($themePath . 'js/datatables/js/jquery.dataTables.min.js'))
				->appendFile($this->basePath($themePath . 'js/datatables/js/dataTables.foundation.min.js'))
				->appendFile($this->basePath($themePath . 'js/app.js'))
			;
			$jsfiles = $oTwitterBootstrap->Config()->get('app')->get('js');
			if (is_array($jsfiles) || ($jsfiles instanceof \Zend\Config\Config)) foreach ($jsfiles as $key => $file) {
			    $this->inlineScript()->appendFile($this->basePath($file));
			}
        ?>
		<?php echo $this->headScript() ?>
      </head>
    <body>
            
			<div class="title-bar" data-responsive-toggle="my-application-main-menu" data-hide-for="medium">
			  <button class="menu-icon" type="button" data-toggle></button>
			  <div class="title-bar-title">Menu</div>
			</div>
			<div class="top-bar" id="my-application-main-menu">
				<div class="top-bar-left">
					<?php
						//$oTwitterBootstrap = $this->bootstrap();
						//$oBootstrapComponents = $oTwitterBootstrap->Components();
						$oNavBar = $oTwitterBootstrap->Navbar('navigation')
							->setUlClass('dropdown menu')
							->setSubUlClass('menu')
							->setSubUlClassLevel1('menu')
							->setDefaultLiClass('')
							->setSubLiClass('')
							->setSubLiClassLevel0('')
							->setMinDepth(0)
							->setMaxDepth(3)
							->setIconPrefixClass('fa fa-')
							//->setHrefSubToggleOverride("#")
							//->setAttributes(array('data-responsive-menu' => 'accordion'))
						;
						$navbar = $oNavBar->render();
						$navbar = str_replace("<ul class=\"dropdown", "<ul data-dropdown-menu class=\"dropdown", $navbar);
						$navbar = str_replace("class=\"dropdown-toggle\"", "", $navbar);
						//$navbar = str_replace("&#x2F;", "/", $navbar);
						//$navbar = str_replace("&#x20;", " ", $navbar);
						echo $navbar;
					?>
				</div>
				<div class="top-bar-right">
					<?php 
						$oLocaleMenu = $oComponents->Languagemenu()
							->setUlClass('dropdown menu')
							->setSubUlClass('menu')
							->setSubUlClassLevel1('menu')
							->setDefaultLiClass('')
							->setSubLiClass('')
							->setSubLiClassLevel0('')
							->setIconPrefixClass('flag-icon flag-icon-')
							->setHrefSubToggleOverride("#")
						;
						$localemenu = $oLocaleMenu->render(); 
						echo str_replace("<ul class=\"dropdown", "<ul data-dropdown-menu class=\"dropdown", $localemenu);
					?>
				</div>
			</div>
        
        <br />
        
        <div class="row columns">
        	<nav role="navigation">
			<?php 
				$oBreadcrumbs = $oTwitterBootstrap->Breadcrumbs('navigation')
					->setHeader( $this->translate('you are here :') )
					->setMinDepth(0)
				;
				$breadcrumb = $oBreadcrumbs->render(); 
				$breadcrumb = str_replace('<ol class="breadcrumb nav-breadcrumb">', '<ul class="breadcrumbs">', $breadcrumb);
				$breadcrumb = str_replace('</ol>', '</ul>', $breadcrumb);
				echo $breadcrumb;
			?>
			</nav>
        </div>
        
		<?php 
			$oToolbarNav = $oComponents->Toolbar('toolbarnavigation');
			if ($oToolbarNav->hasPages()) {
				$oToolbarNav 
					->setUlClass('btn-group btn-group-sm')
					/*->setSubUlClass('')
					->setSubUlClassLevel1('')
					->setDefaultLiClass('')
					->setSubLiClass('')
					->setSubLiClassLevel0('')
					->setMinDepth(0)
					->setMaxDepth(1)*/
					->setIconPrefixClass('fa fa-')
				;
				$toolbarPanel = $oComponents->Panel()
					->setContent( $oToolbarNav->render() )
				;
				?><div class="row columns"><?php echo $toolbarPanel; ?></div><?php
			}
		?>

        <div class="row columns">
            <?php
				echo $this->flashMessenger()->render('error', array('error alert flashmessages'));
				echo $this->flashMessenger()->render('warning', array('warning alert flashmessages'));
				echo $this->flashMessenger()->render('success', array('success alert flashmessages'));
				echo $this->flashMessenger()->render('info', array('info alert flashmessages'));
			?>
		</div>
		
		<div class="row columns container">
			<?php
				$panelLayout = $oComponents->Panel()
					->setHeader( (isset($this->title) ? $this->title : "") )
					->setContent(
						array(
								'tagname' => 'div',
								'classnames' => 'panel-body alert-wrap',
								'content' => $this->content,
						)
					)
				;
				echo $panelLayout;
			?>
			
            <hr>
            <footer>
                <p>
                	<span class="pull-left copyright">&copy; <?php echo date('Y') ?> by <a href="//dragon-projects.net" target="_blank">[dragon-projects.net]</a> - <?php echo $this->translate('All rights reserved.') ?></span>
                	<span class="pull-right poweredby">
                		<?php echo $this->translate('Powered by') ?> &nbsp;
                		<a href="http://php.net" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/php-logo.gif') ?>" height="20" alt="php" /></a> &nbsp;
                		<a href="http://framework.zend.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/zf2-logo.png') ?>" height="16" alt="ZendFramework 2" /></a> &nbsp;
                		<a href="http://www.w3.org/html/" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/html5-badge-h-solo.png') ?>" height="16" alt="HTML5" /></a> &nbsp;
                		<a href="http://jquery.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/jquery-logo.png') ?>" height="16" alt="jQuery" /></a>
                	</span>
               </p>
            </footer>
        </div> <!-- /container -->
        
        <!-- Scripts -->
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
		    $(document).foundation();
		    
			$(document).ready(function() { 
				
			});
        </script>
    </body>
</html>
