<div class="row">
    <div class="col-md-4">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('%s[MyApplication]%s is under active development. If you are interested in following the development of %s[MyApplication]%s, there is a special portal on the official website which provides links to the %s[MyApplication]%s %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<span class="appname">', '</span>', '<span class="appname">', '</span>', '<span class="appname">', '</span>', '<a href="//gitlab.dragon-projects.de:81/zf2/application-base/wikis/home" target="_blank">', '</a>', '<a href="//gitlab.dragon-projects.de:81/zf2/application-base/wikis/blog" target="_blank">', '</a>', '<a href="//gitlab.dragon-projects.de:81/zf2/application-base/issues" target="_blank">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="//gitlab.dragon-projects.de:81/groups/zf2" target="_blank"><?php echo sprintf($this->translate('%s[MyApplication]%s Development Portal'), '<span class="appname">', '</span>') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('We are working on developing a community site to serve as a repository and gallery for %s[MyApplication]%s modules. These projects are available %son our GitLab%s. The site is currently under development and will soon contain a list of some of the modules already available for this application.'), '<span class="appname">', '</span>', '<a href="//gitlab.dragon-projects.de:81/groups/zf2" target="_blank">', '</a>'); ?></p>
                <p><a class="btn btn-success pull-right" href="//gitlab.dragon-projects.de:81/groups/zf2" target="_blank"><?php echo sprintf($this->translate('Explore %s[MyApplication]%s Modules'), '<span class="appname">', '</span>') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while using and/or developing with %s[MyApplication]%s, you can take a look into %shelp section%s or you may reach us via our %ssupport channel%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions via the %scontact form%s.'), '<span class="appname">', '</span>', '<a href="'.$this->url('application/default', array('action' => 'help')).'">', '</a>', '<a href="'.$this->url('application/default', array('action' => 'support')).'">', '</a>', '<a href="'.$this->url('application/default', array('action' => 'support')).'">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/default', array('action' => 'support')); ?>"><?php echo $this->translate('Contact us') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>