<div class="jumbotron">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h2><?php echo sprintf($this->translate('Welcome to %s[MyApplication]%s User Help section'), '<span class="appname">', '</span>') ?></h2>
    <br />
    <p><?php echo $this->translate('here comes your user guidance content...') ?></p>
    <br />
    <p><?php echo sprintf($this->translate('If you need further assistance, please do not hesitate to contact %sMyApplication support%s.<br />'), '<a href="'.$this->url('application/default', array('action' => 'support')).'">', '</a>'); ?></p>
</div>

<?php include 'development_info.phtml'; ?>