<div class="jumbotron">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h2><?php echo sprintf($this->translate('Welcome to %s[MyApplication]%s Support section'), '<span class="appname">', '</span>') ?></h2>
    <br />
    <p><?php echo sprintf($this->translate('Please, take a look into %sMyApplication User Help section%s before you contact support.<br />'), '<a href="'.$this->url('application/default', array('action' => 'help')).'">', '</a>'); ?></p>
    <br />
    <p><?php echo $this->translate('here comes your online support content...') ?></p>
</div>

<?php include 'development_info.phtml'; ?>